### ISSUE TITLE
I used your Trie

### ISSUE THREAD

**Issue by rendall** [mikedeboer/trie#4]
Hello. I used your project and I transcribed it into a Typescript version, that compiles back into your javascript version. You can see them both here:

<https://github.com/rendall/hometown-parser-2/tree/master/lib>

Would you be open to a pull request?

**Comment by rendall** [comment]
Hey @mikedeboer I'm going to go ahead and close this issue, but if you see this and would like that PR, feel free to @ me, or just go ahead and grab it directly: <https://github.com/rendall/hometown-parser-2/blob/master/lib/trie.ts> No need to ask.

**Comment by mikedeboer** [comment]
Hi @rendall, thanks for reaching out! I think having a TS version added would be great :) Please feel free to open a PR at any time.

**Comment by rendall** [comment]
@mikedeboer : Done and tested!
